# ArgumentError: wrong number of arguments (1 for 2)
#   from (irb):1:in `calculate_product'
#   from (irb):4
#   from /Users/username/.rvm/rubies/ruby-2.0.0-p353/bin/irb:12:in `<main>'

def calculate_product(a,b)
  a*b
end

calculate_product(4,2)
# same error when calculate_product 4
